## Artificial Intelligence

Inteligencia artificial son técnicas que permite a una máquina imitar el comportamiento humano.
Machine learning es un subconjunto de la inteligencia artificial en donde se entrena un modelo a partir de un conjunto de datos con el objetivo de tener una respuesta como toma de decisiones o predicciones, el usuario requiere de introducir las características para realizar el entrenamiento del modelo.
Deep learning es un subconjunto de machine learning y se inspira en el comportamiento del cerebro humano, es decir, cuenta con nodos o neuronas, formando una red que busca realizar múltiples combinaciones para obtener diferentes resultados, de esta manera el usuario no requiere indicar al sistema las características del modelo.

Importando librerias

In [1]:
import numpy as np
import matplotlib.pyplot as mp
import pandas as pd

Importando dataset

In [3]:
data = pd.read_csv("Data.csv")
print(data)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


Separar el dataset en dos diferentes variables para separar las dependientes e independientes

In [6]:
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

Importando libreria para realizar proceso de imputación de los datos con el objetivo de reemplazar valores faltantes con la media aritmética.

In [18]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values = np.nan, strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3] = imputer.transform(x[:,1:3])
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


Se realiza una codificación para tener valores numéricos para las variables categóricas y evitar que el sistema mal interprete la codificación (posible efecto categórico que puede cambiar el resultado), se emplea entonces el uso de variables dummy.

In [19]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


In [20]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


Se crea las variables que almacenarán los datos dependientes e independientes para el conjunto de datos de entrenamiento y evaluación, se considera un 20% para la evaluación.

In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

Se realiza una estandarización de los datos para reducir la distancia Euclidiana entre las observaciones.

In [21]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

x_train[:,3:] = sc.fit_transform(x_train[:,3:])
x_test[:,3:] = sc.fit_transform(x_test[:,3:])

print(x_train)
print("------------------------------")
print(x_test)


[[0.0 0.0 1.0 -0.1915918438457856 -1.0781259408412427]
 [0.0 1.0 0.0 -0.014117293757057902 -0.07013167641635401]
 [1.0 0.0 0.0 0.5667085065333239 0.6335624327104546]
 [0.0 0.0 1.0 -0.3045301939022488 -0.30786617274297895]
 [0.0 0.0 1.0 -1.901801144700799 -1.4204636155515822]
 [1.0 0.0 0.0 1.1475343068237056 1.2326533634535488]
 [0.0 1.0 0.0 1.4379472069688966 1.5749910381638883]
 [1.0 0.0 0.0 -0.7401495441200352 -0.5646194287757336]]
------------------------------
[[0.0 1.0 0.0 -1.0 -1.0]
 [1.0 0.0 0.0 1.0 1.0]]


# Regresión lineal

Existe dos tipo de regresiones, la lineal y la logística. Dentro de la lineal se encuentra la simple, que parte de una ecuación lineal (y = b0 + b1*x1)